### PR TITLE
age and B imputation fixes and new features

### PR DESCRIPTION
**Pull request by CeresBarros**
These fixes require using ~`LandR@ageBimputationFixes`~ (now merged into `LandR@development`).

* `imputedPixID`  is a new `sim` object 
* `fireURL` is now a character parameter and has `sourceURL = NA`. Supplying NULL/NA in fireURL turns off age/B imputation inside fire perimeters 
* New parameter to turn on/off the removal of imputed pixels: `rmImputedPix`, defaults to FALSE. /!\ This means that pixels are imputed anyways, but may be removed or not from the simulation.

### CODE REVIEW

**Comment by achubaty** [comment]
please resolve merge conflicts

**Comment by CeresBarros** [comment]
on it and changing lists to same objsts with attributes

**Comment by CeresBarros** [comment]
I believe I've dealt with everything now

**Comment by achubaty** [comment]
if this is in knn2011 branch, then shouldn't we do the PR from there?

**Comment by CeresBarros** [comment]
Well, I thought we agreed to keep PRs small and specific to particular changes

**Comment by achubaty** [comment]
in this case, it's already been merged into the other branch so the streams have been crossed

**Comment by CeresBarros** [comment]
now part of #58

**Pull request closed without merging**
