### PR TITLE
`postProcess` is not cropping/masking properly

### PR DESCRIPTION
**Pull request by CeresBarros**
* need to use `projectRaster` instead, or extents never seem to align properly when using `rawBiomassMap` from Matasci et al 2018 (previously re-projected to 250m resolution) as the basis for RTMLarge

### CODE REVIEW

**Comment by CeresBarros** [comment]
No. I'll try that.

**Comment by CeresBarros** [comment]
Okay I responded without think. Yes I had tried `options("reproducible.useTerra" = TRUE)` on that piece of code (see commented lines). It still won't crop properly, whereas `projectRaster` does. 
I have not tried setting `options("reproducible.useTerra" = TRUE)` at the project level, which may work. However, I think we can't expect other users to change the option and for now I think we may need to use `projectRaster` to make sure the cropping is done properly.

**Comment by CeresBarros** [comment]
UPDATE: setting the option at the project level also doesn't work.

**Review by achubaty — APPROVED** [review]
note: change on line 1414 partially reverts #67 by removing origin check for a SPDF

**Pull request merged**
