### PR TITLE
merge development into master

### PR DESCRIPTION
**Pull request by achubaty**
manual inspection needed to deal with expected conflicts

### CODE REVIEW

**Comment by CeresBarros** [comment]
I would perhaps suggest a rebase of master into development, instead of a PR to avoid merging issues

**Comment by CeresBarros** [comment]
@achubaty I'm wondering if we shouldn't just "rebase" master into the head of development, instead of trying to deal with merge conflicts. Thoughts?

**Comment by achubaty** [comment]
There will be conflicts.

Perhaps rebasing development onto master will make things easier than working through a merge, but it may not.

You can certainly try locally and see how deeply into conflict hell you get 😃 

A more "manual" comparison in a diff editor across the two branches may also be easier since if we are willing to rebase and rewrite history then we only care about the "current state" and not necessarily getting all the changes reflected.

**Comment by CeresBarros** [comment]
sounds good. I'll have a look eventually.

One thing that I'd like before merging into `main` though is to remove as many pkg dependencies coming non main branches (or CRAN) as possible.

**Comment by CeresBarros** [comment]
almost there. still need to look at Rmd

**Comment by CeresBarros** [comment]
@achubaty / @ianmseddy / @eliotmcintire most of the changes in the last year or so were made by you (I think I did some of the terrarizing too). Best if you review the manual, since you know better than me if there were any changes to algorithms worth mentioning

**Comment by CeresBarros** [comment]
I believe we'll have to tackle manuals later.

**Comment by CeresBarros** [comment]
add to rm `development` from build manuals GHA workflow -- it was constantly creating conflicts between `development` and `main` for the md and htlm files

**Review by CeresBarros — APPROVED** [review]
My tests are passing with the MEE paper example. The manual still needs to be reviewed

**Pull request merged**
